### ISSUE TITLE
not install

### ISSUE THREAD

**Issue by mahdisky** [sahilsehwag/pluralsight-downloader-chrome-extension#14]
i cant install,
when running for installing say error

**Comment by JKamsker** [comment]
Can you explain what exactly you did?
Which files are you using?
Have you selected the "pluralsight-downloader-chrome-extension" folder as install directory?

**Comment by mahdisky** [comment]
i runing "pluralsight-downloader-chrome-extension.crx",
and error to install
like this

[https://answers.microsoft.com/en-us/windows/forum/windows_10-files/how-to-fix-this-file-does-not-have-an-app/ee8d3bd0-a29b-40d4-9a1e-d6ac552f0ef7](url)

**Comment by JKamsker** [comment]
Download the git repo with git or zip.
Unpack as folder
Enable dev mode on the chrome plugins page
Import unpacked folder

Do not use the crx
