### ISSUE TITLE
For some course, it only download .smi and not .mp4 files

### ISSUE THREAD

**Issue by shipsywor** [sahilsehwag/pluralsight-downloader-chrome-extension#16]
For some courses like this: https://app.pluralsight.com/library/courses/understanding-distributed-version-control-systems/table-of-contents

It only download .smi files. It does not download .mp4 files.

For other courses, the extension works fine

**Comment by TheSupraLife** [comment]
The course is updated on 27 Jan 2014.
Maybe that will be the issue.

**Comment by richardbang83** [comment]
As @TheSupraLife said, I confirmed that old courses which requires different url are not supported by current version.

**Comment by sahilsehwag** [comment]
@shipsywor Will try to add the support for old courses in future.

**Comment by shipsywor** [comment]
Thank you!

**Comment by alialpha123** [comment]
Support for old courses is added i really want to download some old courses

**Comment by VNRARA** [comment]
I'd love for this to recognize old type content. Also how old is too old for using "latest"?

**Comment by sahilsehwag** [comment]
@VNRARA @alextnull added the support to download the old courses, there is not fixed interval to identify the latest and old course. you can try to download it with `latest` if it doesn't work with that then you can try the `old` option. I might add the support to recognise the old or new course in the future
