### ISSUE TITLE
This extension is not listed in the Chrome Web Store and may have been added without your knowledge.

### ISSUE THREAD

**Issue by heroae1** [sahilsehwag/pluralsight-downloader-chrome-extension#17]
![Screen Shot 2021-04-26 at 12 53 22 PM](https://user-images.githubusercontent.com/80633831/116064148-67aeae00-a68e-11eb-8378-c5c9ed864224.png)
Why this error?
Thanks
This extension is not listed in the Chrome Web Store and may have been added without your knowledge.

**Comment by TheSupraLife** [comment]
It's a kind of false error, because u uploaded it yourself.
I can confirm that the extension is legit.
You don't give any credentials to the extension and the code is legit (you can take a look for it yourself).

**Comment by sahilsehwag** [comment]
Hey, I think you might have to remove the extension, first enable the developer mode and then download and unzip code, go to manage extension page, click on load unpackaged button and select the unzipped folder. This should work, for reference you can follow this guide(https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked)
