### ISSUE TITLE
Failed to download 

### ISSUE THREAD

**Issue by ahmed-esmail** [sahilsehwag/pluralsight-downloader-chrome-extension#32]
i got this error when try to download
![image](https://user-images.githubusercontent.com/51207001/127071235-d426fe65-7637-4599-ae59-09fc5f1d123c.png)

**Comment by sahilsehwag** [comment]
Hey @ahmed-esmail 
This seems like an older version of the extension, Can you try this with the latest version of the code and let us know here?

**Comment by ahmed-esmail** [comment]
I download from this link 
https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/releases/tag/v0.3-alpha

**Comment by ahmed-esmail** [comment]
Thanks it's working now
