### ISSUE TITLE
Saving files?

### ISSUE THREAD

**Issue by app-js** [sahilsehwag/pluralsight-downloader-chrome-extension#33]
Hi, is it possible for the downloaded videos to be saved automatically? Or is that normal?

**Comment by alextnull** [comment]
> Hi, is it possible for the downloaded videos to be saved automatically? Or is that normal?

Just disable this option in chrome settings.
![image](https://user-images.githubusercontent.com/72241501/127962598-12cf94b3-7c4f-4b5d-a315-1d067c89f44e.png)

**Comment by sahilsehwag** [comment]
Closing this, since this is a browser settings, and not related to the extension
