### ISSUE TITLE
Add a random jitter to the waiting duration

### ISSUE THREAD

**Issue by 0xShamil** [sahilsehwag/pluralsight-downloader-chrome-extension#34]
In the current implementation, the waiting time between two consecutive downloads is constant. A slightly better approach might be to introduce a small random jitter to change the waiting time in each download by a small margin (say 1 to 5 seconds), to make it difficult for the automation detection algorithms to kick-in.

(Apologies for not submitting a PR along with this request, I barely know any JS to be of help.)

**Comment by sahilsehwag** [comment]
merged the pr
