### ISSUE TITLE
TypeError: name.replace is not a function

### ISSUE THREAD

**Issue by ressomatic** [sahilsehwag/pluralsight-downloader-chrome-extension#38]
It seems the code still uses 'a' and 's' keybinds. When trying to execute download, error pops up.

**Comment by ressomatic** [comment]
Fixed it by replacing const nameToFilename = (name) => name.replace(...).trim(); with:

const nameToFilename = (name) => name.toString().replace(/[\/:?><]/g, " ");

**Comment by sahilsehwag** [comment]
Hey this issue was already fixed, you are using old version of extension, please install the latest version by downloading the code as zip and loading the extension in chrome using Load Unpacked button in Manage Extensions page in chrome
