### ISSUE TITLE
How to build latest version?

### ISSUE THREAD

**Issue by xT4Z1N4TRx** [sahilsehwag/pluralsight-downloader-chrome-extension#41]
Hi,

Latest release is over a year old but i see code has been updated since then. How do I build the latest version pls?

**Comment by sahilsehwag** [comment]
Hi, @xT4Z1N4TRx,
You can download the code with latest changes, and then load the plugin by following steps:
* Enable developer mode in chrome
* Click on "load unpacked extension" button
* Navigate and select the unzipped folder of extension(which contains manifest file)

If you face any problem, you can comment here and I'll try to resolve it, closing the issue
