### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by farmerpabs** [sahilsehwag/pluralsight-downloader-chrome-extension#42]
Hi there! The extension doesn't seem to do anything when I click any "e" "s" or "c" buttons. Attached is a screenshot of the installed extension. I tried installing in 2 different browsers. The extension icon shows grey also and not red like the screenshots. Any help would be appreciated!

![image](https://user-images.githubusercontent.com/98192212/150608653-4e45a992-3a0b-429b-9c67-6d767d587c0f.png)

**Comment by chrispaivacwb** [comment]
It didn't work around here too.
Just version 0.1 and 0.2 works for me.

**Comment by farmerpabs** [comment]
hi @chrispaivacwb, do you know where I can find versions 0.1 and 0.2? Thanks.

**Comment by sahilsehwag** [comment]
Hey @farmerpabs , the keybindings is not supported in latest versions, in new versions we have new UI to do all the same tasks. Please install by downloading the code and install using `Load Unpackaged Extension` button in google chrome

**Comment by farmerpabs** [comment]
![image](https://user-images.githubusercontent.com/98192212/151253737-dd81e065-0ffb-4277-bf40-8bbe0b8890cc.png)

Hello @sahilsehwag, thanks for your response. I installed it by using the Load Unpackaged Extension button in Chrome but I don't see the full UI like in the screenshots. Mine looks like the picture above. What am I doing wrong?
