### ISSUE TITLE
Extension is grayed out and doesn't show the UI

### ISSUE THREAD

**Issue by farmerpabs** [sahilsehwag/pluralsight-downloader-chrome-extension#43]
![image](https://user-images.githubusercontent.com/98192212/151454459-a489ed46-10fd-4de2-8b21-7b3884e942e5.png)

Hello, I sent this message in a closed ticket so I wasn't sure if anyone was notified. I installed it by using the Load Unpackaged Extension button in Chrome but I don't see the full UI like in the screenshots. Mine looks like the picture above. What am I doing wrong?

My pluralsight access is expiring at the end of the month and would like to get this fixed so I can download a few courses. Any help would be much appreciated! Thank you!

**Comment by farmerpabs** [comment]
I've even tried it in a completely new Chrome profile and the same thing happened.

**Comment by chrispaivacwb** [comment]
@farmerpabs remove all previews loaded version and get the last one published.
I was having same issues like you and then I see last version published.
https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/releases/tag/v0.5beta
After load this one I think it will solve your problems.

**Comment by sahilsehwag** [comment]
@farmerpabs use as the latest release, as mentioned above by @chrispaivacwb , that will solve your problem, please let us know if you face any problem

**Comment by sahilsehwag** [comment]
@farmerpabs closing this issue, If you face any problem, you can reopen this issue, and comment here

**Comment by farmerpabs** [comment]
Thank you that worked!

**Comment by rossanag** [comment]
Hello I downloaded the latest version 0.6.0 but it's grayed as well, any suggestion? Thanks
