### ISSUE TITLE
Never Downloads

### ISSUE THREAD

**Issue by Debdut** [sahilsehwag/pluralsight-downloader-chrome-extension#44]
I followed the instructions here -- https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension#usage

But nothing happens or downloads!

**Comment by Chikuma1** [comment]
This does still work, used it today. downloading the .crx didn't work for me either, what I had to do was get the source code(zip) unzip it and then load unpacked. It works for both chrome and Opera GX (as it uses chrome extensions)

Can find the latest build here:
https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/releases/tag/v0.5beta
