### ISSUE TITLE
No longer downloads video

### ISSUE THREAD

**Issue by secretclean** [sahilsehwag/pluralsight-downloader-chrome-extension#49]
I was using this extension without issue on weekly free courses for about 6 months without issue. It's only recently, after the change from free weekly courses to free MONTHLY courses, that the video downloading portion no longer works. I also tested some courses that I own, and the video no longer downloads for those either.

The playlist file, exercise.zip file, and vtt files all download without any problems. It's only the video that is not downloadable, even when logged in and attempting to download courses I own. Anyone else unable to download video?

**Comment by sclihua** [comment]
It works, thank you @rjdp.
