### ISSUE TITLE
Manifest version 2 is deprecated...

### ISSUE THREAD

**Issue by VNRARA** [sahilsehwag/pluralsight-downloader-chrome-extension#52]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

Nothing big, just a heads up

**Comment by sahilsehwag** [comment]
@VNRARA thanks a lot for this update

**Comment by JudithGo** [comment]
Copy this in your manifest file:

{
	"manifest_version": 3,
	"name": "PluralsightCourseDownloaderExtension",
	"description": "Download entire course from Pluralsight easilty",
	"version": "0.1.0",
	"author": "Sahil Sehwag",
	"homepage_url": "https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension",
	"content_scripts": [
		{
			"matches": ["https://app.pluralsight.com/*"],
			"js": ["lib/jquery.slim.min.js", "src/script.js"],
			"run_at": "document_end"
		}
	],
	"background": {
		"service_worker": "src/background.js"
	  },
	"action": {
		"default_icon": {
			"16": "images/extension_icon_16.png",
			"32": "images/extension_icon_32.png",
			"48": "images/extension_icon_48.png",
			"128": "images/extension_icon_128.png"
		},
		"default_title": "Pluralsight Downloader",
		"default_popup": "src/popup.html"
	},
	"permissions": ["activeTab", "declarativeContent", "storage", "downloads", "notifications", "unlimitedStorage"]
}

**Comment by Daniel4hmed** [comment]
> {
> "manifest_version": 3,
> "name": "PluralsightCourseDownloaderExtension",
> "description": "Download entire course from Pluralsight easilty",
> "version": "0.1.0",
> "author": "Sahil Sehwag",
> "homepage_url": "https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension",
> "content_scripts": [
> {
> "matches": ["https://app.pluralsight.com/*"],
> "js": ["lib/jquery.slim.min.js", "src/script.js"],
> "run_at": "document_end"
> }
> ],
> "background": {
> "service_worker": "src/background.js"
> },
> "action": {
> "default_icon": {
> "16": "images/extension_icon_16.png",
> "32": "images/extension_icon_32.png",
> "48": "images/extension_icon_48.png",
> "128": "images/extension_icon_128.png"
> },
> "default_title": "Pluralsight Downloader",
> "default_popup": "src/popup.html"
> },
> "permissions": ["activeTab", "declarativeContent", "storage", "downloads", "notifications", "unlimitedStorage"]
> }

Does not work at all. Have removed the folders from js arrays and `src/` from service_worker.

**Comment by Daniel4hmed** [comment]
> @VNRARA - @sahilsehwag - Copy this in manifest file:
> 
> { "manifest_version": 3, "name": "PluralsightCourseDownloaderExtension", "description": "Download entire course from Pluralsight easilty", "version": "0.1.0", "author": "Sahil Sehwag", "homepage_url": "https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension", "content_scripts": [ { "matches": ["https://app.pluralsight.com/*"], "js": ["lib/jquery.slim.min.js", "src/script.js"], "run_at": "document_end" } ], "background": { "service_worker": "src/background.js" }, "action": { "default_icon": { "16": "images/extension_icon_16.png", "32": "images/extension_icon_32.png", "48": "images/extension_icon_48.png", "128": "images/extension_icon_128.png" }, "default_title": "Pluralsight Downloader", "default_popup": "src/popup.html" }, "permissions": ["activeTab", "declarativeContent", "storage", "downloads", "notifications", "unlimitedStorage"] }

Works great! Thank you!

**Comment by grzglo** [comment]
There is a typo in the above proposal, easilty → easily.
