### ISSUE TITLE
missing crx

### ISSUE THREAD

**Issue by samascience** [sahilsehwag/pluralsight-downloader-chrome-extension#60]
![github issue](https://user-images.githubusercontent.com/4021146/205547954-cb566bff-af76-4c34-ba12-a071c9599706.jpg)

issue with the downloaded extension, missing crx

**Comment by arminanton** [comment]
Chrome will prevent to download extensions not signed. So, you have to right click on the extension link, then go to Save Link As, and save the file where you wish. Next, you must extract that file (for example, using 7Zip). Then, you will have a folder with it. Open Extensions panel in Chrome, activate Developer Mode, and select Load unpacked extension. Then load one video from the desired course, and while the player is going, with your mouse on the of the player screen, hit `e` then `c` and then head to the extension. I suggest changing the wait time to 7 seconds and hit apply. You should then see in a few the extension downloading video by video of the course.

One know bug is that sometimes the Course title in the extension gets stuck with the first course you downloaded in that day. However, it does not affect the ability to properly download the courses.

The extension downloads and organizes the modules into folders for you, and also automatically downloads the assignments and subtitles.

Congrats to the dev that worked on this! 👍
