### ISSUE TITLE
The extension is not working 

### ISSUE THREAD

**Issue by AbdulAzizSabra** [sahilsehwag/pluralsight-downloader-chrome-extension#68]
Hi,

The extension was working perfect yesterday, but today is not working on mac. 

What should I do?

**Comment by AbdulAzizSabra** [comment]
The video Url look like this: https://app.pluralsight.com/ilx/video-courses/a5358191-d8ee-496d-8fb7-b871d3bbc720/ef2ae631-87f1-4a03-8e4d-19d941f4f549/f09490be-a978-43f9-835a-06cb627c54bd

**Comment by sahilsehwag** [comment]
- Then the reason is same as what was mentioned in above issue
- You can try out the things I mentioned in that thread
- Closing this issue for now, since its already being tracked in the issue mentioned above

**Comment by AbdulAzizSabra** [comment]
but the thread above since two days and the extension was working by me yesterday?

**Comment by sahilsehwag** [comment]
@AbdulAzizSabra 
- These changes are rolled out incrementally
- Your region probably didn't received this feature 2 days ago
